"""Wrap the built Player in a Windows installer.

    python tools/build_exe.py          # first: make dist/Player
    python tools/build_installer.py    # then: make the Setup EXE

Produces one file to sign and one file to publish. Signing happens at publish
and only through Azure, so this never signs and never talks to Azure.

Two decisions worth knowing about:

**It installs per user, with no administrator prompt.** A disc player should not open with a UAC dialog, and a per-user install is
the one anybody can remove again without help. The cost is that two people
sharing a machine each install their own copy, which is a fair trade.

**It associates nothing.** A disc player that quietly takes over ``.iso`` on
first run is the kind of software this one is meant not to be. If somebody
wants that, they can set it themselves.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from wti_player.version import APP_NAME, MUTEX_NAME, PUBLISHER, VERSION  # noqa: E402

DIST = REPO / "dist"
PAYLOAD = DIST / "Player"

sys.path.insert(0, str(REPO / "tools"))
import licence_notice  # noqa: E402

#: Stable for the life of the product: Inno uses it to recognise an existing
#: install and upgrade it in place. Changing it would leave people with two.
APP_ID = "{{9E4F1C2A-6B8D-4E77-9A31-7C0D5B2E8F44}"

ISCC_CANDIDATES = (
    Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"),
    Path(r"C:\Program Files\Inno Setup 6\ISCC.exe"),
)


def find_iscc() -> Path:
    for candidate in ISCC_CANDIDATES:
        if candidate.is_file():
            return candidate
    raise SystemExit(
        "Inno Setup 6 is not installed.\n"
        "  winget install JRSoftware.InnoSetup"
    )


def slug(name: str) -> str:
    return "".join(part for part in name.title() if part.isalnum())


def write_iss(path: Path, *, output_base: str) -> Path:
    script = f"""; Generated by tools/build_installer.py — edit that, not this.
[Setup]
AppId={APP_ID}
AppName={APP_NAME}
AppVersion={VERSION}
AppVerName={APP_NAME} {VERSION}
AppPublisher={PUBLISHER}
AppPublisherURL=https://wetheindies.com
DefaultDirName={{autopf}}\\{APP_NAME}
DefaultGroupName={APP_NAME}
DisableProgramGroupPage=yes
OutputDir={DIST}
OutputBaseFilename={output_base}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; No administrator prompt, and no dialog offering one either. Offering the
; choice means half of everyone installs into Program Files, which needs an
; elevation prompt on a program that has no reason to want one — and a
; download from a small studio asking for administrator is the moment people
; close the window.
PrivilegesRequired=lowest
; A running Player holds this mutex. Setup sees it and asks the person to
; close the Player instead of replacing files under it; the Player's own
; update path releases the mutex before it starts Setup silently.
AppMutex={MUTEX_NAME}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayName={APP_NAME}
UninstallDisplayIcon={{app}}\\Player.exe
SetupIconFile={REPO / "wti_player" / "ui" / "player.ico"}
; What people are agreeing to: the GPL, and the list of what is inside.
LicenseFile={REPO / "dist" / "LICENSE-NOTICE.txt"}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a shortcut on the desktop"; GroupDescription: "Shortcuts:"; Flags: unchecked

; Upgrading over an older build leaves that build's files behind unless they
; are named. A VLC plugin we stopped shipping stays on disk and stays
; loadable, so the runtime an upgraded machine uses is not the one we test.
[InstallDelete]
Type: filesandordirs; Name: "{{app}}\\_internal\\vlc\\plugins"
Type: filesandordirs; Name: "{{app}}\\_internal\\PyQt6"
Type: files; Name: "{{app}}\\_internal\\*.pyd"

[Files]
Source: "{PAYLOAD}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{APP_NAME}"; Filename: "{{app}}\\Player.exe"
Name: "{{group}}\\Uninstall {APP_NAME}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{APP_NAME}"; Filename: "{{app}}\\Player.exe"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\Player.exe"; Description: "Open {APP_NAME}"; Flags: nowait postinstall skipifsilent
; The Player's own update path runs Setup silently with /relaunch=1 and has
; already closed itself; this brings the new Player back up for the person.
Filename: "{{app}}\\Player.exe"; Flags: nowait; Check: WantsRelaunch

[Code]
function WantsRelaunch: Boolean;
begin
  Result := ExpandConstant('{{param:relaunch|0}}') = '1';
end;
"""
    path.write_text(script, encoding="utf-8")
    return path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args(argv)

    if not (PAYLOAD / "Player.exe").is_file():
        raise SystemExit("dist/Player is empty — run: python tools/build_exe.py")

    iscc = find_iscc()
    notice_path = DIST / "LICENSE-NOTICE.txt"
    notice_path.parent.mkdir(parents=True, exist_ok=True)
    notice_path.write_text(licence_notice.notice(), encoding="utf-8")
    output_base = f"{slug(APP_NAME)}-Setup-{VERSION}"
    script = write_iss(REPO / "tools" / "player.iss", output_base=output_base)
    print(f"script -> {script}")

    result = subprocess.run([str(iscc), str(script)], cwd=str(REPO), check=False)
    if result.returncode != 0:
        return result.returncode

    installer = DIST / f"{output_base}.exe"
    print(f"\n{installer}")
    print(f"  {installer.stat().st_size / 1_048_576:.1f} MB")
    print(f"  sha256 {sha256(installer)}")
    print(
        "\nUnsigned. Sign this one file with Azure at publish, then put its "
        "URL, its version and\nits *post-signing* SHA-256 into the website's "
        "three NEXT_PUBLIC_PLAYER_* variables."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
